name: Examples

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - development
      - master
      - release

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-test
        make install-examples
        make install
    - name: Run examples
      run: |
        make examples
